name: Notion Sync

on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, labeled, unlabeled, assigned, unassigned, milestoned, demilestoned, reopened, closed]

jobs:
  notion_job:
    runs-on: ubuntu-latest
    name: Add Github PR to Notion
    steps:
      - run: npm -v
