name: Notion Sync

on:
  workflow_dispatch:
  issues:
    types: [opened, edited, labeled, unlabeled, assigned, unassigned, milestoned, demilestoned, reopened, closed]

jobs:
  notion_job:
    runs-on: ubuntu-latest
    name: Add GitHub Issues to Notion
    steps:
			- uses: actions/checkout@v3 
			- uses: actions/setup-node@v3
				with:
					node-version: '14' 
			- run: npm install